### ISSUE TITLE
my portals gets broken in original game

### ISSUE THREAD

**Issue by Vidzhet** [xoxor4d/p2-rtx#10]
my portals gets broken in original game after rtx remix ver, prolly something wrong with config
![image](https://github.com/user-attachments/assets/5aedfca4-137e-437c-b85d-c8d771f4983b)

**Comment by xoxor4d** [comment]
Known issue but there is nothing I can do about that unfortunately.
You'll have to set `r_portal_stencil_depth` to `2` manually (console or config)

**Comment by Vidzhet** [comment]
thank you. for others: in original game create autoexec.cfg file in your Portal 2\\portal2\\cfg and paste this line in that file: r_portal_stencil_depth 2

**Comment by Nico00007566** [comment]
Is there anything else that the mod breaks from the original game? (i reinstall but had to use the command for the portals)

**Comment by kkzz23** [comment]
> Is there anything else that the mod breaks from the original game? (i reinstall but had to use the command for the portals)

For sure. In my case there is shading error, I mean game looks ugly, bridges outside chambers are overly bright

**Comment by Nico00007566** [comment]
> > Is there anything else that the mod breaks from the original game? (i reinstall but had to use the command for the portals)
> 
> For sure. In my case there is shading error, I mean game looks ugly, bridges outside chambers are overly bright

Do you know any way to restore all the configuration through the console? steam cloud does not allow you to restore everything from 0.

**Comment by kkzz23** [comment]
I would say game reinstall in my case. I haven't tried it tbh yet. But I
think it should work with repairing shading

wt., 3 gru 2024, 20:09 użytkownik Gonzalo ***@***.***>
napisał:

**Comment by Windcomet36** [comment]
hello, i recently installed the RTX mod and uninstalled it after seeing it didn't run well enough and now doors are broken, showing a white background before stepping through them, and portals are no longer see through and bridges are very bright. i would appreciate if someone, anyone still here, can tell me what i should do to get this fixed please.

**Comment by xoxor4d** [comment]
> hello, i recently installed the RTX mod and uninstalled it after seeing it didn't run well enough and now doors are broken, showing a white background before stepping through them, and portals are no longer see through and bridges are very bright. i would appreciate if someone, anyone still here, can tell me what i should do to get this fixed please.
> 

Follow: "How do I disable remix?" mentioned on the main GitHub page

**Comment by Windcomet36** [comment]
> > hello, i recently installed the RTX mod and uninstalled it after seeing it didn't run well enough and now doors are broken, showing a white background before stepping through them, and portals are no longer see through and bridges are very bright. i would appreciate if someone, anyone still here, can tell me what i should do to get this fixed please.
> 
> Follow: "How do I disable remix?" mentioned on the main GitHub page

I've already deleted the rtx files and uninstalled and reinstalled Portal 2 a few times already.

**Comment by xoxor4d** [comment]
It's not about deleting files. You need to enter reset console variables

**Comment by Windcomet36** [comment]
> It's not about deleting files. You need to enter reset console variables

Ok, I'll see what i can do. How do i fix this if i dont have the "toggle-p2-rtx.bat?" do i need to install the rtx mod again to fix everything?

**Comment by xoxor4d** [comment]
I ... it's only about the dvars

**Comment by Windcomet36** [comment]
> I ... it's only about the dvars

im sorry, im a bit too slow, bare with me pls. what are the dvars?

**Comment by xoxor4d** [comment]
Open the ingame console and type in the mentioned console variables

**Comment by Windcomet36** [comment]
> Open the ingame console

It worked! thank you so much. srry to bother u a lot with my dumb behavior
