### ISSUE TITLE
FATAL ERROR MH_INIT_STATUS != MH_STATUS :: MH_OK Error

### ISSUE THREAD

**Issue by matheeshapathirana** [xoxor4d/p2-rtx#100]
No game crash, after entering to the single player mode I got this error
![image](https://github.com/user-attachments/assets/4cbbe5c3-e2dd-4e20-8011-c59e43323555)

here's all the log files,
[bridge64.log](https://github.com/user-attachments/files/18039122/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/18039123/remix-dxvk.log)
[bridge32.log](https://github.com/user-attachments/files/18039124/bridge32.log)

**Comment by HashVOLTing** [comment]
Have you installed Nvidia RTX Remix? https://www.nvidia.com/en-us/geforce/rtx-remix/

**Comment by xoxor4d** [comment]
You'll have to buy the game on Steam. Pirated copies are not supported
