### ISSUE TITLE
Failed to create a D3D device!

### ISSUE THREAD

**Issue by rwolf2467** [xoxor4d/p2-rtx#101]
When executing the .bat file, I get the following messages:
![Screenshot 2024-12-08 140528](https://github.com/user-attachments/assets/ce6942b3-8968-492b-bc6a-ce3d2c6382cb)

Here are the logs:
[bridge32.log](https://github.com/user-attachments/files/18052216/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/18052218/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/18052221/remix-dxvk.log)

I use a Nvidia RTX 4060.

Edit: I have tried it with the instructions here on github and again with instructions on youtube. The same error with both.

**Comment by xoxor4d** [comment]
Closing this - duplicate
* Please try whats mentioned in the last two comments in #18  and leave another comment if that fixes your issue or not 👍

**Comment by rwolf2467** [comment]
I have just tried the solution mentioned there. Unfortunately, I still get the same error.
