### ISSUE TITLE
keep crashing at the startup

### ISSUE THREAD

**Issue by dhruv-bca** [xoxor4d/p2-rtx#102]
I followed every instructions but still whenever i try to open the batch file it starts the portal 2 but then after showing an image it crashes 

system specs:

32 gb ddr4 3200mhz ram
amd ryzen 5 5600 
rtx 3070
ssd nvme 2.0

https://github.com/user-attachments/assets/f3f8ddcb-caa9-4bbb-9dcc-8f9744cc6f77

**Comment by xoxor4d** [comment]
Im seeing folders in there that shouldn't be there .. anyhow, is that a legit portal 2 installation?

**Comment by dhruv-bca** [comment]
> Im seeing folders in there that shouldn't be there .. anyhow, is that a legit portal 2 installation?

no it is from fitgirl 

wouldn't i downloaded the real portal 2 with rtx if i'd have legit portal 2.  (asking not commenting)

sorry for bad english.

**Comment by xoxor4d** [comment]
> no it is from fitgirl

Pirated copies are not supported.
