### ISSUE TITLE
Portals arent see-through  (after deleting installed rtx files)

### ISSUE THREAD

**Issue by Capzay** [xoxor4d/p2-rtx#110]
![image](https://github.com/user-attachments/assets/40d0eec1-d00b-431f-a8e2-135653c79e7f)

i used the rtx mod, but it ran like shit on my pc (rtx 3080). i also wanted to play P2 normally, but now my portals are fucked after deleting the files i dragged into the game files

also reinstalled the game, and it didnt work, so i reinstalled using depot_downloader, still didnt work

**Comment by Capzay** [comment]
![image](https://github.com/user-attachments/assets/29336905-1189-47fd-85fb-a353a523de43)
apparently my portals do this when inside them aswell

**Comment by Capzay** [comment]
bruh its fixed:
r_portal_stencil_depth 2

**Comment by Pietrodjaowjao** [comment]
How do i fix this permanently?
