### ISSUE TITLE
Fsr frame gen in P2-RTX?

### ISSUE THREAD

**Issue by filispeen** [xoxor4d/p2-rtx#111]
Is it possible to replace dlssg with fsr frame generation?

**Comment by xoxor4d** [comment]
Why are you creating an issue for a question that should go into: https://github.com/xoxor4d/p2-rtx/discussions ?

That question is not really related to this compatibility mod (more of a general rtx-remix question) -> I don't think that there is a proper working solution for that. I could be wrong tho. Closing this.
