### ISSUE TITLE
Unexpected portal2.exe hash

### ISSUE THREAD

**Issue by v0vanch0** [xoxor4d/p2-rtx#115]
[!][INIT FAILED] Not loading P2-RTX Compatibility Mod
---------------> Unexpected portal2.exe hash. Hash was: 393ca001b796245e2d5425dd3505627810daecf8
---------------> Path was: E:\Portal 2\portal2.exe
---------------> Failed to find main window with name: Portal 2 - Direct3D 9

        Make sure that:
        - Steam is running.
        - That it is a legit copy of the game.
        - That you followed the install instructions and installed everything correctly.

        Please copy/paste the contents of this window when you open a GitHub issue.

**Comment by xoxor4d** [comment]
`R.G. Catalyst` ..... `- That it is a legit copy of the game.`
Buy the game

**Comment by v0vanch0** [comment]
😭
