### ISSUE TITLE
Portals not showing up

### ISSUE THREAD

**Issue by epicEaston197** [xoxor4d/p2-rtx#13]
I followed the installation instructions everything works including transparency and stuff I followed the installation guide to fix that but my portals aren't visible
![image](https://github.com/user-attachments/assets/b930d884-08b3-4840-bdda-1e36b3a1335e)

Please tell me if I'm doing anything wrong
This is what my portal two directory looks like
![image](https://github.com/user-attachments/assets/eb7561a0-9489-40ba-bf69-4c17580d1d3c)
I am making this issue because there's nothing in the installation guide that helps the users troubleshoot if there's no portal visual

**Comment by epicEaston197** [comment]
Fixed it by just downloading and re extracting the contents from `Portal 2\p2-rtx_1.4_d54a4fb.zip\portal2_root` Hopefully this will help someone out there that encounters the same issue
![image](https://github.com/user-attachments/assets/3760a006-409f-4e6e-8bdb-47a02e1a3bca)

**Comment by tylertn001** [comment]
Having the same issue, even after a complete reinstall of the game.
