### ISSUE TITLE
Boosted brightness

### ISSUE THREAD

**Issue by Crappy-Productions** [xoxor4d/p2-rtx#17]
There are parts of the game where is either too dark to see what's ahead of you
![Screenshot 2024-11-22 220643](https://github.com/user-attachments/assets/217532e9-e924-48fe-84ee-4f157fa7d8d0)
or the lighting doesn't resemble anything close to the orginal, ruining the feel
![Screenshot 2024-11-23 063854](https://github.com/user-attachments/assets/a3cefa34-d8f3-4451-8df6-3e3359e68086)
I think a boosted brightness in those parts are needed for visibility sake.

**Comment by sambow23** [comment]
This mod is made purely for compatibility for portal 2, if a map lacks lighting, you or someone else would need go to use the nvidia remix toolkit to add lights.

**Comment by xoxor4d** [comment]
I appreciate you taking an interest in this mod. This is not really an issue with the compatibility mod itself tho.
This has to be handled by you, or other people that want to remaster the game using the rtx remix toolset (like stated above)

Issues that would be related to the compatibility mod for example:
- crashes
- broken particle effects
- invisible things that should be rendered
- broken portals
- co-op issues
