### ISSUE TITLE
"Windows cannot find 'portal2.exe'. Make sure you typed the name correctly, and then try again."

### ISSUE THREAD

**Issue by 58ThatOnePerson85** [xoxor4d/p2-rtx#19]
When i press _start_portal2_rtx it gives me this error. im new to this and have no idea what im doing. yes i put the files where they need to be. Just need more explaining because im not that smart. thanky

**Comment by xoxor4d** [comment]
Please post a screenshot of the folder where you put the files into

**Comment by 58ThatOnePerson85** [comment]
![Screenshot 2024-11-26 151207](https://github.com/user-attachments/assets/6307e771-53ae-4dec-b076-42b85bcd64f7)
i think this is where its supposed to go right?

**Comment by xoxor4d** [comment]
Not sure how you ended up downloading the repository itself but ... please .. just follow the instructions found in the readme. You need to download the release

**Comment by 58ThatOnePerson85** [comment]
Okay my bad. did everything, it works. the only problem i NOW have is that the portals dont show. when i shoot one its invisible but the portal IS there. just not able to see it

**Comment by xoxor4d** [comment]
> Okay my bad. did everything, it works. the only problem i NOW have is that the portals dont show. when i shoot one its invisible but the portal IS there. just not able to see it

Duplicate of https://github.com/xoxor4d/p2-rtx/issues/13
