### ISSUE TITLE
/toolsblack materials have inconsistent rendering

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#2]
Depending on the map sometimes tools/toolsblack materials are invisible, sometimes some of the materials are a random material that exists in the map, and sometimes they render correctly

Texture names from left to right
tools/toolsblack
tools/toolsblack_cheap
tools/toolsblack_noportal
tools/toolsblack_nofog
tools/toolsblack_skybox

Material swap example screenshot (first run):
<img width="1280" alt="Untitled" src="https://github.com/user-attachments/assets/0a57fe07-e6e0-4fa5-922a-41be9c1e99a7">

Material swap example screenshot (second run):
<img width="1280" alt="Untitled" src="https://github.com/user-attachments/assets/315147f1-4ede-4304-b669-dc44f2c0eacd">

Original rasterized game:
![image](https://github.com/user-attachments/assets/ad4b5489-f5c1-4d65-8422-e41bb8703521)

Workshop incorrect invisible material test map:
https://steamcommunity.com/sharedfiles/filedetails/?id=216474249

Workshop incorrect invisible material: tools/toolsblack_noportal

Workshop incorrect invisible material example:
https://www.youtube.com/watch?v=3silFQP_IMw

**Comment by xoxor4d** [comment]
Brush models that use any tool texture are currently set to no-render as they are mostly used for area portals.
Have to find a better way to fix this.

```cpp
// disable areaportals
else if (ff_bmodel::s_shader && mesh->m_VertexFormat == 0x80003 && ctx.info.material_name.starts_with("tools/")
	&& !(g_player_current_area == 6 && map_settings::is_level.sp_a1_wakeup)) // do not disable elevator "door" on wakeup
{
	ctx.modifiers.do_not_render = true; 
}
```

I assume that the brushes on the test map are not brush models? I'll see where it handles that and will manually assign a black texture to fix that

**Comment by WolfeStrider** [comment]
Yeah I made them as world brushes, oops. Let me know and I'll recompile the map with func_brushes if you need me to
