### ISSUE TITLE
Some effects have precision/explosion issues

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#32]
Bug reported by wolfe_strider on Trello on November 5th

Description:
This mainly happens with the portal gun fire effect but it does happen occasionally with the grab effect

Examples:
https://www.youtube.com/watch?v=lorWx6aYRHA
https://www.youtube.com/watch?v=ify1GixvkGg
https://www.youtube.com/watch?v=xmdhW12JXUE
![Image](https://github.com/user-attachments/assets/cc2e039a-45f9-42d2-8d7e-cb767d1931dd)
Preview image:
![Image](https://github.com/user-attachments/assets/4e911937-e02a-4cd6-9116-709865beb14f)

**Comment by xoxor4d** [comment]
This should be "fixed enough" to not be a problem anymore. Can you confirm that @wolfestridershooter ?

**Comment by WolfeStrider** [comment]
> This should be "fixed enough" to not be a problem anymore. Can you confirm that @wolfestridershooter ?

Sorry for the really late response but yes this seems to be 100% fixed. Great work as always!
