### ISSUE TITLE
Timer is z-fighting with itself

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#36]
Bug reported by wolfe_strider on Trello on November 5th

Description:
Yet another map I can’t record on for some reason sp_a4_jump_polarity

Example:
![Image](https://github.com/user-attachments/assets/3a518c6c-3501-44ad-ac8c-b5bef0769ee6)

**Comment by xoxor4d** [comment]
This was fixed with a recent commit that marked the timer slices as decals in the rtx.conf.
I've also made the timer backgrounds emissive in the yet to be updated remix-mod
