### ISSUE TITLE
Transparencies don't work

### ISSUE THREAD

**Issue by capybarych** [xoxor4d/p2-rtx#4]
Transparency of portals, glass and water does not work. My specs: RTX 3060 laptop, Ryzen 5600H
![Снимок экрана (496)](https://github.com/user-attachments/assets/1646211e-d2d8-4f59-80e5-76c25e808236)
![Снимок экрана (497)](https://github.com/user-attachments/assets/e242dc26-2261-49ac-8448-9c54c1b0ad54)
![Снимок экрана (498)](https://github.com/user-attachments/assets/b3eae8d0-c8c5-495e-8457-fa38c732cb12)

**Comment by xoxor4d** [comment]
Download and extract both zip files as instructed in the readme. You are missing the `remix_mod.zip`
