### ISSUE TITLE
Culling still occurs with brush models and props with -xo_disable_all_culling commandline arg

### ISSUE THREAD

**Issue by WolfeStrider** [xoxor4d/p2-rtx#41]
Bug reported by wolfe_strider on Trello on November 7th

Description:
Self explanatory

Examples:
https://www.youtube.com/watch?v=A6EKTHyC32A
https://www.youtube.com/watch?v=VZMhPRd1jNo
Preview image:
![Image](https://github.com/user-attachments/assets/4c935c80-c72f-4a63-909e-1983d679ea60)

**Comment by xoxor4d** [comment]
This commandline arg is no longer available
