### ISSUE TITLE
All I get is a gray screen in game

### ISSUE THREAD

**Issue by Johnnycyan** [xoxor4d/p2-rtx#5]
I downloaded both of the zip files in the release section and extracted the files into my portal 2 root directory, copied the sound cache. launched with the bat file. changed the video settings. When I go in game all I see is gray with a crosshair. If I turn off ray-tracing in the rtx remix settings I see a kind of messed up version of the world with almost no textures.

Tried reinstalling portal 2, same issue. Tried with just one or the other zip file, same issue. Tried reinstalling the game, running it first, then installing the mod, same issue. Is there something I am missing?

Specs:
Ryzen 5950x
RTX 4090
64GB Ram
Windows 11 23H2

**Comment by xoxor4d** [comment]
Could you try replacing your rtx.conf in the root folder with this? [rtxconf.zip](https://github.com/user-attachments/files/17807312/rtxconf.zip)

**Comment by Johnnycyan** [comment]
> Could you try replacing your rtx.conf in the root folder with this? [rtxconf.zip](https://github.com/user-attachments/files/17807312/rtxconf.zip)

Same problem, nothing changed.

**Comment by Johnnycyan** [comment]
And just to confirm, I am supposed to install BOTH zip file contents correct?

**Comment by xoxor4d** [comment]
Correct. Contents of portal2-root folder go into your root folder. Can you post a screenshot? Also, is alt+x showing the remix menu?

**Comment by Johnnycyan** [comment]
> Correct. Contents of portal2-root folder go into your root folder. Can you post a screenshot? Also, is alt+x showing the remix menu?

Yeah the menu shows. This is with raytracing enabled.
![image](https://github.com/user-attachments/assets/3e622b6e-03a2-4105-a687-784e1dc1277b)

this is without.
![image](https://github.com/user-attachments/assets/9db6ceec-ed09-4efb-ae65-71cb754e604a)

**Comment by xoxor4d** [comment]
Running the latest steam version?
You are the first one to report such a serious issue .. so not really sure what could cause that

**Comment by Johnnycyan** [comment]
> Running the latest steam version? You are the first one to report such a serious issue .. so not really sure what could cause that

Yes. I freshly installed it again to try out this mod so it's the newest version with nothing else on it. Even tested reinstalling the game without installing the mod just to make sure the game itself was fine and it ran without issues.

**Comment by xoxor4d** [comment]
Does the window title say rtx?

**Comment by Johnnycyan** [comment]
> Does the window title say rtx?

Yes. I actually just thought maybe it could be because of my ultrawide monitor. I set my monitor to 2560x1440 instead and it's now working. So I guess ultrawide breaks it.

**Comment by Johnnycyan** [comment]
Yeah so this is fixed so gonna close the issue
