### ISSUE TITLE
"unable to load _rtx.asi"

### ISSUE THREAD

**Issue by Zachattack525** [xoxor4d/p2-rtx#6]
I've followed the installation instructions but I'm just getting this error every time I run the bat file.

**Comment by xoxor4d** [comment]
Could you take a screenshot of the error? Any antivirus that might think it is a malicious file and blocking it?

**Comment by Zachattack525** [comment]
![image](https://github.com/user-attachments/assets/142a0739-fcd8-490d-b45e-f2684f74b824)

**Comment by xoxor4d** [comment]
Could you download the tool that it suggests and take a screenshot of the dependencies it shows .. or that it shows are missing? You'll most certainly have to open the asi file with that program

**Comment by Zachattack525** [comment]
I'm not certain what I'm supposed to be dragging into here: 
![image](https://github.com/user-attachments/assets/8e12066a-5299-448b-91b0-ab1b4d8d8924)

**Comment by xoxor4d** [comment]
The asi file that you can find in the bin folder

**Comment by ebuggingSam123** [comment]
Download [this](https://www.microsoft.com/en-ie/download/details.aspx?id=8109) and run the exe, after that open DXSETUP.EXE in the directory you selected and it should install some stuff which you need.
