### ISSUE TITLE
Lasers and most lights do not work

### ISSUE THREAD

**Issue by FluffyPuppyKasey** [xoxor4d/p2-rtx#7]
![image](https://github.com/user-attachments/assets/ebf2f3a3-0037-4ce6-b064-0de83f7ab4ad)
![image](https://github.com/user-attachments/assets/44ff7915-4e19-46a4-8c71-e3b7f3c46677)
![image](https://github.com/user-attachments/assets/55d36576-ff44-4dbb-b0be-1ca39d988fc7)

This is just one example, but I'm sure there's many others. The lasers look like they have refraction, instead of just being transparent, also the videos on the displays have no colour and cast no light

**Comment by xoxor4d** [comment]
It's currently impossible to get the original colors of the videos working.
The only option is to tint the entire thing and make it emissive, I've actually did that on a few elevator videos (blue tint). 

But that is something the people remastering the game will have to do. Same goes for the laser textures and lights. That is something you'd do with the remix toolkit and is out of the scope of the compatibility mod.

**Comment by FluffyPuppyKasey** [comment]
> It's currently impossible to get the original colors of the videos working. The only option is to tint the entire thing and make it emissive, I've actually did that on a few elevator videos (blue tint).
> 
> But that is something the people remastering the game will have to do. Same goes for the laser textures and lights. That is something you'd do with the remix toolkit and is out of the scope of the compatibility mod.

Ahh, that makes sense
