### ISSUE TITLE
p2-rtx support linux native or linux + wine or not?

### ISSUE THREAD

**Issue by KnoyanMitsu** [xoxor4d/p2-rtx#8]
this project support linux or linux + wine or not. if yes any docummentation to install it? if support wine how to install it?

**Comment by KingVulpes** [comment]
I tried installing it on my Steam Deck, and sadly I think the ASI loader is just incompatible with Linux

**Comment by xoxor4d** [comment]
It is not supported from my site. If it works, great. If not, you are out of luck unfortunately. I'll gladly accept a PR that makes it work under linux tho.
